### ISSUE TITLE
Error in RP-Authentication response-correct-state-value.json

### ISSUE THREAD

**Issue by Sciumegpp00** [stfbk/mig#3]
The test is created with a double test suite [https://github.com/stfbk/mig/blob/master/testplans/spid-cie-oidc/implementations/spid-cie-oidc-django/input/mig-t/tests/single/RP/RP-Authentication%20response-correct-state-value.json](test)

**Comment by marche271** [comment]
Closing this issue as it was due tue a typo. The typo has been corrected in the commit b96ead3b63aefc57970a8367792f5415f799140b, which resolves the issue. Thanks for the report.
